export const ERR = {
  COMMON: {
    INTERNAL_ERROR: "INTERNAL_ERROR",
    NOT_FOUND: "NOT_FOUND",
    BAD_REQUEST: "BAD_REQUEST",
    UNAUTHORIZED: "UNAUTHORIZED",
    FORBIDDEN: "FORBIDDEN",
    INVALID_PAYLOAD: "INVALID_PAYLOAD",
  },
  AUTH: {
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    INVALID_TOKEN: "INVALID_TOKEN",
    INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
    INVALID_ACCESS_TOKEN: "INVALID_ACCESS_TOKEN",
    TOKEN_EXPIRED: "TOKEN_EXPIRED",
    REFRESH_TOKEN_INVALID: "REFRESH_TOKEN_INVALID",
    REFRESH_REUSE_DETECTED: "REFRESH_REUSE_DETECTED",
    REFRESH_NOT_REGISTERED: "REFRESH_NOT_REGISTERED",
    NO_TOKEN_PROVIDED: "NO_TOKEN_PROVIDED",
    SESSION_NOT_FOUND: "SESSION_NOT_FOUND",
    ACCESS_TOKEN_EXPIRED: "ACCESS_TOKEN_EXPIRED",
  },
  USER: {
    NOT_FOUND: "USER_NOT_FOUND",
    EMAIL_IN_USE: "EMAIL_IN_USE",
    AVATAR_UPLOAD_FAILED: "AVATAR_UPLOAD_FAILED",
    INVALID_ID: "INVALID_ID",
    USERNAME_REQUIRED: "USERNAME_REQUIRED",
    USERNAME_TAKEN: "USERNAME_TAKEN",
  },
  POST: {
    NOT_FOUND: "POST_NOT_FOUND",
    NOT_OWNER: "POST_NOT_OWNED",
  },
  COMMENT: {
    NOT_FOUND: "COMMENT_NOT_FOUND",
    NOT_OWNER: "COMMENT_NOT_OWNED",
  },
  LIKE: {
    ALREADY_EXISTS: "LIKE_ALREADY_EXISTS",
    NOT_FOUND: "LIKE_NOT_FOUND",
    INVALID_TARGET_TYPE: "INVALID_TARGET_TYPE",
    ALREADY_LIKED: "ALREADY_LIKED",
    NOT_YET_LIKED: "NOT_YET_LIKED",
  },
  FAVORITE: {
    ALREADY_EXISTS: "FAVORITE_ALREADY_EXISTS",
    NOT_FOUND: "FAVORITE_NOT_FOUND",
    REQUIRED_ID: "REQUIRED_ID",
  },
  FOLLOWER: {
    ALREADY_FOLLOWING: "FOLLOWER.ALREADY_FOLLOWING",
    NOT_FOLLOWING: "FOLLOWER.NOT_FOLLOWING",
    CANNOT_FOLLOW_SELF: "FOLLOWER.CANNOT_FOLLOW_SELF",
  },
  SEARCH: {
    NO_RESULTS: "NO_RESULTS",
    INVALID_QUERY: "INVALID_QUERY",
  },
  FEED: {
    NO_FOLLOWING: "NO_FOLLOWING",
  },
  FOLLOW: {
    SELF_FOLLOW: "SELF_FOLLOW",
    ALREADY_FOLLOWING: "ALREADY_FOLLOWING",
    NOT_FOLLOWING: "NOT_FOLLOWING",
  },
} as const;

export type ErrorCode = {
  [G in keyof typeof ERR]: (typeof ERR)[G][keyof (typeof ERR)[G]];
}[keyof typeof ERR];
